### ISSUE TITLE
Plugin importation does not work properly in tw 5.1.4

### ISSUE THREAD

**Issue by Spangenhelm** [TheDiveO/TW5FontAwesome#1]
Hi, first of all thank you for your wonderful work and efforts !

My problem appeared when i was trying to import your plugin in my tw. i have realised that there is a little issue with the link you have provided on your [demonstration page](http://thediveo.github.io/TW5FontAwesome/output/fontawesome.html#Font%20Awesome)

The link `$:/plugins/TheDiveO/FontAwesome/fonts/FontAwesome` appear to not be the right link (it is just the stylesheet, not the plugin itself, thus tw does not recognize it as one)

I think the right link is [this one](http://thediveo.github.io/TW5FontAwesome/output/fontawesome.html#%24%3A%2Fplugins%2FTheDiveO%2FFontAwesome) but ~~when i try to import by drag'n'drop it does not create all the needed tiddlers, they all appear in the list but are all "empty" because they do not exist (they are not created on import..)~~ edit: my bad i just have forgotten to refresh my tw, the docs was not clear enough on this point so i have published a pull request to enhance it (it is awaiting validation by jeremy)

Ps: there is a new version (4.3) of fontawesome, i have seen that you have provided instructions to update but do you mind updating your plugin ? this way everyone could enjoy it without hassle..

Once again thank you!
Spangenhelm

**Comment by diego898** [comment]
@Spangenhelm - I am still having this problem on 5.1.13 even after a refresh? I only import one tiddler that is the stylesheet and it isnt marked shadow or anything.

**Comment by diego898** [comment]
In order to actually install it I had to search "plugins" using advanced search - system - and then drag the link to fontawesome to my tiddlywiki in order to get it to work
